### ISSUE TITLE
Se a classe Repository não cria o contexto, não pode ser ela a chamar o dispose

### ISSUE THREAD

**Issue by luizcarlosfaria** [GlebsonS4ntos/ProcessamentoArquivos#1]
https://github.com/GlebsonS4ntos/ProcessamentoArquivos/blob/d4aa2797e70b74692ce64ad97239bbd31f8a2aa1/src/ProcessamentoArquivos.Infraestructure/Repositories/Repository.cs#L49-L53

você está interferindo no ciclo de vida de forma equivocada

**Comment by GlebsonS4ntos** [comment]
Opa, resolvi, mas queria saber se deveria implementar o Dispose no context ou n precisaria ja que o entity ja tem o dispose automatico
