### ISSUE TITLE
Exception Replace - 

### ISSUE THREAD

**Issue by luizcarlosfaria** [GlebsonS4ntos/ProcessamentoArquivos#2]
https://github.com/GlebsonS4ntos/ProcessamentoArquivos/blob/d4aa2797e70b74692ce64ad97239bbd31f8a2aa1/src/ProcessamentoArquivos.Service/Validations/ClienteValidator.cs#L68-L70

Você substituiu uma exception por outra, levando apenas o Message da exception Original.

Em vez disso, use

```cs
} catch(Exception ex) { 
   throw;
}
```

**Comment by GlebsonS4ntos** [comment]
Opa, fiz a correção vlw <3
